from __future__ import annotations

from string.templatelib import Template
from typing import Annotated, Any

from ._profiles import JsonProfile, TomlProfile, YamlProfile

type JsonTemplate = Annotated[Template, "json"]
type TomlTemplate = Annotated[Template, "toml"]
type YamlTemplate = Annotated[Template, "yaml"]

type ExceptionSpan = tuple[tuple[int, int], tuple[int, int]]
type ExceptionDiagnostic = dict[str, object]

class TemplateError(Exception):
    code: str | None
    span: ExceptionSpan | None
    diagnostics: tuple[ExceptionDiagnostic, ...]
    ...

class TemplateParseError(TemplateError): ...
class TemplateSemanticError(TemplateError): ...
class UnrepresentableValueError(TemplateSemanticError): ...

def render_json(
    template: JsonTemplate, *, profile: JsonProfile | str | None = ...
) -> Any: ...
def render_json_text(
    template: JsonTemplate, *, profile: JsonProfile | str | None = ...
) -> str: ...
def render_toml(
    template: TomlTemplate, *, profile: TomlProfile | str | None = ...
) -> Any: ...
def render_toml_text(
    template: TomlTemplate, *, profile: TomlProfile | str | None = ...
) -> str: ...
def render_yaml(
    template: YamlTemplate, *, profile: YamlProfile | str | None = ...
) -> Any: ...
def render_yaml_text(
    template: YamlTemplate, *, profile: YamlProfile | str | None = ...
) -> str: ...
