from __future__ import annotations

from string.templatelib import Template
from typing import Any

from ._profiles import JsonProfile, TomlProfile, YamlProfile

type ExceptionSpan = tuple[tuple[int, int], tuple[int, int]]
type ExceptionDiagnostic = dict[str, object]

class TemplateError(Exception):
    code: str | None
    span: ExceptionSpan | None
    diagnostics: tuple[ExceptionDiagnostic, ...]
    ...

class TemplateParseError(TemplateError): ...
class TemplateSemanticError(TemplateError): ...
class UnrepresentableValueError(TemplateSemanticError): ...

def render_json(
    template: Template, *, profile: JsonProfile | str | None = ...
) -> Any: ...
def render_json_text(
    template: Template, *, profile: JsonProfile | str | None = ...
) -> str: ...
def render_toml(
    template: Template, *, profile: TomlProfile | str | None = ...
) -> Any: ...
def render_toml_text(
    template: Template, *, profile: TomlProfile | str | None = ...
) -> str: ...
def render_yaml(
    template: Template, *, profile: YamlProfile | str | None = ...
) -> Any: ...
def render_yaml_text(
    template: Template, *, profile: YamlProfile | str | None = ...
) -> str: ...
