from __future__ import annotations

from string.templatelib import Template
from typing import Any

# Non-public extension module retained for internal imports and packaging
# compatibility. Public callers should use `tstring_bindings`.

type ExceptionSpan = tuple[tuple[int, int], tuple[int, int]]
type ExceptionDiagnostic = dict[str, object]

class TemplateError(Exception):
    code: str | None
    span: ExceptionSpan | None
    diagnostics: tuple[ExceptionDiagnostic, ...]
    ...

class TemplateParseError(TemplateError): ...
class TemplateSemanticError(TemplateError): ...
class UnrepresentableValueError(TemplateSemanticError): ...

__contract_version__: int
__contract_symbols__: tuple[str, ...]

def render_json(template: Template, profile: str = ...) -> Any: ...
def render_json_text(template: Template, profile: str = ...) -> str: ...
def _render_json_result_payload(
    template: Template, profile: str = ...
) -> tuple[str, Any]: ...
def render_toml(template: Template, profile: str = ...) -> Any: ...
def render_toml_text(template: Template, profile: str = ...) -> str: ...
def _render_toml_result_payload(
    template: Template, profile: str = ...
) -> tuple[str, Any]: ...
def render_yaml(template: Template, profile: str = ...) -> Any: ...
def render_yaml_text(template: Template, profile: str = ...) -> str: ...
def _render_yaml_result_payload(
    template: Template, profile: str = ...
) -> tuple[str, Any]: ...
